In [ ]:
#!/usr/bin/env python

import numpy as np
import copy
from planner_interface_2 import planner_interface

if __name__ == "__main__":
    ## Setup initial Values in the planner
    sim = True
    goal = np.array([0.85, 0.35, 0.45, 0.])*100.

    if sim:
        x = np.array([81., -14., 30., 157.])
        mu = np.array([81., -14., 30., 157.])
        planner = planner_interface(goal, sim, x, mu)
    else:
        planner = planner_interface(goal, sim)

    mu = copy.copy(planner.mu_actual)
    x = copy.copy(planner.x_actual)

    max_threshold = 0.02
    max_final_error = 10.
    replanning_threshld = 50.
    planner.planner.nSegments = 10
    planner.t = 20
    planner.planner.dyna.goal_threshold = max_threshold

    ## Data Collection for Post-Processing and Plots
    traj = [planner.mu_actual]
    traj_true = [planner.x_actual]
    cov_traj = [planner.cov_actual[planner.id1]]
    ds_traj = [planner.wts_actual]
    
    mu_plan, s_plan, u_plan = planner.generate_plan()

    print "Planned Path: \n", np.round(mu_plan, 3)

POMDP-HD Set
start_mu:  [ 81. -14.  30. 157.]
start_cov: [[10.  0.  0.  0.]
 [ 0. 10.  0.  0.]
 [ 0.  0. 10.  0.]
 [ 0.  0.  0. 10.]] 
goal:  [85. 35. 45.  0.]
In Planner, 
start_mu:  [ 81. -14.  30. 157.] 
start_cov: [[10.  0.  0.  0.]
 [ 0. 10.  0.  0.]
 [ 0.  0. 10.  0.]
 [ 0.  0.  0. 10.]]
set of continuous state Goals: 
[array([ 85., -15.,  16., 157.]), array([ 85., -15.,  -8.,  70.]), array([ 85., -15., -20.,   0.]), array([ 85., -15.,  30.,   0.]), array([85., 35., 45.,  0.])]
end_ds =  3 , with wts:  [0. 0. 0. 1. 0.]
Start mu:  [ 81. -14.  30. 157.]
start_ds = 0 , with wts:  [1. 0. 0. 0. 0.]
All possible rollouts :  [[0, 1, 2, 3]]

******************************************************
Inputs:
mu =  [ 81. -14.  30. 157.] 
covInit =  [[10.  0.  0.  0.]
 [ 0. 10.  0.  0.]
 [ 0.  0. 10.  0.]
 [ 0.  0.  0. 10.]] 
wtsInit =  [1. 0. 0. 0. 0.] 
goal =  [ 85. -15.  16. 157.]

******************************************************
  Could not determine Jacobian structure from user input